# Personal GitHub Pages Configuration

# Site settings
title: My Personal Site
description: This is my personal GitHub Pages site.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://rodrodd.github.io"  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
